### ISSUE TITLE
Difficulty trying to apply more than one constraint to optimization

### ISSUE THREAD

**Issue by tmabdev** [yunshengtian/AutoOED#13]
Hi !

I am having troubles trying to apply multiple constraints to my design variables. To reproduce my case : 

1. create a problem with 4 variables, 2 objectives and 2 constraints
2. create a constraint.py file with constraints x1 - x2 and x1 - x3
3. try to generate samples (5 in my example), an error pop :
<img width="296" alt="image" src="https://user-images.githubusercontent.com/90194797/225427762-a436dbd4-5078-4b69-8dfd-ef3c549dc532.png">

I think the problem comes from the evaluate_feasible() in problem.py, more specifically this call to pymoo when G contains multiple constraint evaluations : 

Problem.calc_constraint_violation(np.column_stack(np.atleast_2d(G))).

If you need more informations please tell me.

**Comment by yunshengtian** [comment]
Hi, 

Thank you so much for the bug report! Yes indeed here the column_stack call is not necessary. I have fixed that in my most recent commit just now.

**Comment by tmabdev** [comment]
Hi, 

Many thanks, it appears ok to me !
